version: '3.0'
services:
    talebook:
        image: talebook/talebook
        container_name: talebook
        ports:
            - '8078:80'
        volumes:
            - ./data:/data
        restart: unless-stopped