version: '3.3'

services:
  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    restart: always
    environment:
    - TZ=Asia/Shanghai
    ports:
    - 1314:80
    - 3012:3012
    volumes:
    - './vault-data:/data'
    env_file:
    - ./vault.env

