version: "3"
services:
  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis:/data

  busuanzi:
    image: "dejavumoe/busuanzi:latest"
    ports:
      - "8080:8080"
    volumes:
       - ./data/busuanzi:/app/expose
    links:
      - redis
    depends_on:
      - redis
    environment:
      LOG_ENABLE: true
      API_SERVER: http:\/\/127.0.0.1:8080\/api